### PR TITLE
Refactored number parsing

### PR DESCRIPTION
**Pull request by mpnovikova**
Simplified and refactored number parsing. All 117 unit tests are passing

### CODE REVIEW

**Comment by creationix** [comment]
Great work!  Sorry I didn't see this sooner, I've been traveling for work.

The only question I have is do we want the new lenient behavior where it will parse invalid numbers without throwing an error?  For example, try parsing `"[12--e-e]"`.  Since all the number parsing states were merged into one, it will now accept nearly any combination of the allowed characters.  The `parseFloat` builtin will simply parse till it hits an error and ignore the rest without throwing an error.

**Comment by mattsgarlata** [comment]
`JSON.parse` would throw an error in that case rather than accept the invalid number.  It's nice to make things fault tolerant, but with JSON parsing being such a low level activity, it may make more sense to match the behavior of `JSON.parse` so there are no surprises.

**Comment by mpnovikova** [comment]
I replaced parseFloat() with Number which for `12--e-e` will yield `NaN` which should be inline with `JSON.parse` behavior. I am leaving the special check for the long string of digits because I need it for my project. It may not be kosher/orthodox JavaScript but it must work with Citrix for this project. Community may remove it if they want. However I would love it to stay there so I can keep this repo up to date. Instead of being stuck with one version I patched.

**Comment by mattsgarlata** [comment]
I had a thought.  If someone needs to have an exception thrown you could perhaps compare things that come out as NaN and see if their original input was the String "NaN", and throw an exception in that case.

**Comment by mpnovikova** [comment]
Original NaN string won't make into this block it will be parsed as a string earlier.

**Comment by mpnovikova** [comment]
@creationix would you mind bumping up a version on this repo so the `npm install` could pick it up? Thank you

**Comment by mattsgarlata** [comment]
OK @mpnovikova.  I'm not really worried about this change, but thought I should bring up the exception handling in case anyone else had a strong opinion about it.

It certainly was impressive how much code you were able to remove in this pull request!

**Comment by mpnovikova** [comment]
Thank you! 

Certainly a good point special `Number` values such as `NaN`, `Infinity`, `MINIMUM_VALUE`, and `MAXIMUM_VALUE` will be treated like strings but they are special numbers and should be treated as such.

**Comment by creationix** [comment]
@mpnovikova I believe your changes are in the latest release.  Let me know if you need anything else.

**Comment by mpnovikova** [comment]
Thank you @creationix

**Pull request merged**
